server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://localhost:8081/
          predicates:
          - Path=/book/**
        - id: film
          uri: http://localhost:8082/
          predicates:
          - Path=/film/**